/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PushBetEscrow {
  export type BetStruct = {
    betId: BigNumberish;
    creator: AddressLike;
    title: string;
    description: string;
    option1: string;
    option2: string;
    option1Amount: BigNumberish;
    option2Amount: BigNumberish;
    totalAmount: BigNumberish;
    endTime: BigNumberish;
    status: BigNumberish;
    result: BigNumberish;
    winner: AddressLike;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
  };

  export type BetStructOutput = [
    betId: bigint,
    creator: string,
    title: string,
    description: string,
    option1: string,
    option2: string,
    option1Amount: bigint,
    option2Amount: bigint,
    totalAmount: bigint,
    endTime: bigint,
    status: bigint,
    result: bigint,
    winner: string,
    createdAt: bigint,
    completedAt: bigint
  ] & {
    betId: bigint;
    creator: string;
    title: string;
    description: string;
    option1: string;
    option2: string;
    option1Amount: bigint;
    option2Amount: bigint;
    totalAmount: bigint;
    endTime: bigint;
    status: bigint;
    result: bigint;
    winner: string;
    createdAt: bigint;
    completedAt: bigint;
  };

  export type DisputeStruct = {
    betId: BigNumberish;
    disputer: AddressLike;
    reason: string;
    status: BigNumberish;
    arbitrator: AddressLike;
    createdAt: BigNumberish;
    resolvedAt: BigNumberish;
  };

  export type DisputeStructOutput = [
    betId: bigint,
    disputer: string,
    reason: string,
    status: bigint,
    arbitrator: string,
    createdAt: bigint,
    resolvedAt: bigint
  ] & {
    betId: bigint;
    disputer: string;
    reason: string;
    status: bigint;
    arbitrator: string;
    createdAt: bigint;
    resolvedAt: bigint;
  };
}

export interface PushBetEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "assignArbitrator"
      | "bets"
      | "cancelBet"
      | "completeBet"
      | "createBet"
      | "createDispute"
      | "disputes"
      | "emergencyWithdraw"
      | "feeRecipient"
      | "getBet"
      | "getDispute"
      | "getPlatformStats"
      | "getUserBets"
      | "joinBet"
      | "nextBetId"
      | "owner"
      | "paymentToken"
      | "platformFee"
      | "pushChannel"
      | "pushComm"
      | "renounceOwnership"
      | "resolveDispute"
      | "setFeeRecipient"
      | "setPlatformFee"
      | "setPushChannel"
      | "setPushComm"
      | "totalBets"
      | "totalVolume"
      | "transferOwnership"
      | "userBets"
      | "userLosses"
      | "userWinnings"
      | "withdrawWinnings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetCancelled"
      | "BetCompleted"
      | "BetCreated"
      | "BetJoined"
      | "DisputeCreated"
      | "DisputeResolved"
      | "FundsWithdrawn"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assignArbitrator",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "bets", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "cancelBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeBet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBet",
    values: [string, string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDispute",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinBet",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextBetId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pushChannel",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pushComm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPushChannel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPushComm",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "totalBets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userBets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userLosses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userWinnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawWinnings",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignArbitrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextBetId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pushComm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPushChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPushComm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userBets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userLosses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawWinnings",
    data: BytesLike
  ): Result;
}

export namespace BetCancelledEvent {
  export type InputTuple = [
    betId: BigNumberish,
    creator: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    betId: bigint,
    creator: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    betId: bigint;
    creator: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetCompletedEvent {
  export type InputTuple = [
    betId: BigNumberish,
    winner: AddressLike,
    winnings: BigNumberish,
    result: BigNumberish
  ];
  export type OutputTuple = [
    betId: bigint,
    winner: string,
    winnings: bigint,
    result: bigint
  ];
  export interface OutputObject {
    betId: bigint;
    winner: string;
    winnings: bigint;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetCreatedEvent {
  export type InputTuple = [
    betId: BigNumberish,
    creator: AddressLike,
    title: string,
    endTime: BigNumberish,
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [
    betId: bigint,
    creator: string,
    title: string,
    endTime: bigint,
    totalAmount: bigint
  ];
  export interface OutputObject {
    betId: bigint;
    creator: string;
    title: string;
    endTime: bigint;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetJoinedEvent {
  export type InputTuple = [
    betId: BigNumberish,
    participant: AddressLike,
    amount: BigNumberish,
    isOption1: boolean
  ];
  export type OutputTuple = [
    betId: bigint,
    participant: string,
    amount: bigint,
    isOption1: boolean
  ];
  export interface OutputObject {
    betId: bigint;
    participant: string;
    amount: bigint;
    isOption1: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeCreatedEvent {
  export type InputTuple = [
    betId: BigNumberish,
    disputer: AddressLike,
    reason: string
  ];
  export type OutputTuple = [betId: bigint, disputer: string, reason: string];
  export interface OutputObject {
    betId: bigint;
    disputer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    betId: BigNumberish,
    arbitrator: AddressLike,
    result: BigNumberish
  ];
  export type OutputTuple = [betId: bigint, arbitrator: string, result: bigint];
  export interface OutputObject {
    betId: bigint;
    arbitrator: string;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PushBetEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): PushBetEscrow;
  waitForDeployment(): Promise<this>;

  interface: PushBetEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  assignArbitrator: TypedContractMethod<
    [_betId: BigNumberish, _arbitrator: AddressLike],
    [void],
    "nonpayable"
  >;

  bets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        betId: bigint;
        creator: string;
        title: string;
        description: string;
        option1: string;
        option2: string;
        option1Amount: bigint;
        option2Amount: bigint;
        totalAmount: bigint;
        endTime: bigint;
        status: bigint;
        result: bigint;
        winner: string;
        createdAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;

  cancelBet: TypedContractMethod<[_betId: BigNumberish], [void], "nonpayable">;

  completeBet: TypedContractMethod<
    [_betId: BigNumberish, _result: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBet: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _option1: string,
      _option2: string,
      _endTime: BigNumberish,
      _initialAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  createDispute: TypedContractMethod<
    [_betId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  disputes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, bigint] & {
        betId: bigint;
        disputer: string;
        reason: string;
        status: bigint;
        arbitrator: string;
        createdAt: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getBet: TypedContractMethod<
    [_betId: BigNumberish],
    [PushBetEscrow.BetStructOutput],
    "view"
  >;

  getDispute: TypedContractMethod<
    [_betId: BigNumberish],
    [PushBetEscrow.DisputeStructOutput],
    "view"
  >;

  getPlatformStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, string] & {
        _totalBets: bigint;
        _totalVolume: bigint;
        _platformFee: bigint;
        _feeRecipient: string;
      }
    ],
    "view"
  >;

  getUserBets: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  joinBet: TypedContractMethod<
    [_betId: BigNumberish, _isOption1: boolean, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextBetId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  pushChannel: TypedContractMethod<[], [string], "view">;

  pushComm: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [_betId: BigNumberish, _result: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [_newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPushChannel: TypedContractMethod<
    [_newChannel: AddressLike],
    [void],
    "nonpayable"
  >;

  setPushComm: TypedContractMethod<
    [_newPushComm: AddressLike],
    [void],
    "nonpayable"
  >;

  totalBets: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userBets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userLosses: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userWinnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawWinnings: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assignArbitrator"
  ): TypedContractMethod<
    [_betId: BigNumberish, _arbitrator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        betId: bigint;
        creator: string;
        title: string;
        description: string;
        option1: string;
        option2: string;
        option1Amount: bigint;
        option2Amount: bigint;
        totalAmount: bigint;
        endTime: bigint;
        status: bigint;
        result: bigint;
        winner: string;
        createdAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelBet"
  ): TypedContractMethod<[_betId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeBet"
  ): TypedContractMethod<
    [_betId: BigNumberish, _result: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createBet"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _option1: string,
      _option2: string,
      _endTime: BigNumberish,
      _initialAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDispute"
  ): TypedContractMethod<
    [_betId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, bigint] & {
        betId: bigint;
        disputer: string;
        reason: string;
        status: bigint;
        arbitrator: string;
        createdAt: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBet"
  ): TypedContractMethod<
    [_betId: BigNumberish],
    [PushBetEscrow.BetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDispute"
  ): TypedContractMethod<
    [_betId: BigNumberish],
    [PushBetEscrow.DisputeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlatformStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, string] & {
        _totalBets: bigint;
        _totalVolume: bigint;
        _platformFee: bigint;
        _feeRecipient: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBets"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "joinBet"
  ): TypedContractMethod<
    [_betId: BigNumberish, _isOption1: boolean, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextBetId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pushChannel"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pushComm"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [_betId: BigNumberish, _result: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPushChannel"
  ): TypedContractMethod<[_newChannel: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPushComm"
  ): TypedContractMethod<[_newPushComm: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalBets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userBets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userLosses"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userWinnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawWinnings"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BetCancelled"
  ): TypedContractEvent<
    BetCancelledEvent.InputTuple,
    BetCancelledEvent.OutputTuple,
    BetCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BetCompleted"
  ): TypedContractEvent<
    BetCompletedEvent.InputTuple,
    BetCompletedEvent.OutputTuple,
    BetCompletedEvent.OutputObject
  >;
  getEvent(
    key: "BetCreated"
  ): TypedContractEvent<
    BetCreatedEvent.InputTuple,
    BetCreatedEvent.OutputTuple,
    BetCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BetJoined"
  ): TypedContractEvent<
    BetJoinedEvent.InputTuple,
    BetJoinedEvent.OutputTuple,
    BetJoinedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeCreated"
  ): TypedContractEvent<
    DisputeCreatedEvent.InputTuple,
    DisputeCreatedEvent.OutputTuple,
    DisputeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BetCancelled(uint256,address,uint256)": TypedContractEvent<
      BetCancelledEvent.InputTuple,
      BetCancelledEvent.OutputTuple,
      BetCancelledEvent.OutputObject
    >;
    BetCancelled: TypedContractEvent<
      BetCancelledEvent.InputTuple,
      BetCancelledEvent.OutputTuple,
      BetCancelledEvent.OutputObject
    >;

    "BetCompleted(uint256,address,uint256,uint8)": TypedContractEvent<
      BetCompletedEvent.InputTuple,
      BetCompletedEvent.OutputTuple,
      BetCompletedEvent.OutputObject
    >;
    BetCompleted: TypedContractEvent<
      BetCompletedEvent.InputTuple,
      BetCompletedEvent.OutputTuple,
      BetCompletedEvent.OutputObject
    >;

    "BetCreated(uint256,address,string,uint256,uint256)": TypedContractEvent<
      BetCreatedEvent.InputTuple,
      BetCreatedEvent.OutputTuple,
      BetCreatedEvent.OutputObject
    >;
    BetCreated: TypedContractEvent<
      BetCreatedEvent.InputTuple,
      BetCreatedEvent.OutputTuple,
      BetCreatedEvent.OutputObject
    >;

    "BetJoined(uint256,address,uint256,bool)": TypedContractEvent<
      BetJoinedEvent.InputTuple,
      BetJoinedEvent.OutputTuple,
      BetJoinedEvent.OutputObject
    >;
    BetJoined: TypedContractEvent<
      BetJoinedEvent.InputTuple,
      BetJoinedEvent.OutputTuple,
      BetJoinedEvent.OutputObject
    >;

    "DisputeCreated(uint256,address,string)": TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;
    DisputeCreated: TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;

    "DisputeResolved(uint256,address,uint8)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
