/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockPushComm,
  MockPushCommInterface,
} from "../../contracts/MockPushComm";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "channel",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "identity",
        type: "bytes",
      },
    ],
    name: "NotificationSent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_channel",
        type: "address",
      },
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_identity",
        type: "bytes",
      },
    ],
    name: "sendNotification",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100165761011f908161001c8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c63ba3d69d714602857600080fd5b3460e557606036600319011260e5576001600160a01b0390600435828116919082900360e15760243592831680930360e1576044359067ffffffffffffffff80831160dd573660238401121560dd57826004013590811160dd57366024828501011160dd57818160409260247f0e4b44fb38eac0331850c1153816cc5b44ae83beaac9977aa7a1a41033969d37966020855282602086015201848401378181018301889052601f01601f19168101030190a380f35b8580fd5b8380fd5b5080fdfea264697066735822122058f13817a2cd72987acc90d394b77fd24771c7b1e6115c6b3ef090dab8304a3264736f6c63430008140033";

type MockPushCommConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockPushCommConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockPushComm__factory extends ContractFactory {
  constructor(...args: MockPushCommConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockPushComm & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockPushComm__factory {
    return super.connect(runner) as MockPushComm__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockPushCommInterface {
    return new Interface(_abi) as MockPushCommInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockPushComm {
    return new Contract(address, _abi, runner) as unknown as MockPushComm;
  }
}
