/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pushBetEscrowSol from "./PushBetEscrow.sol";
export type { pushBetEscrowSol };
export type { MockERC20 } from "./MockERC20";
export type { MockPushComm } from "./MockPushComm";
