/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockPushCommInterface extends Interface {
  getFunction(nameOrSignature: "sendNotification"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NotificationSent"): EventFragment;

  encodeFunctionData(
    functionFragment: "sendNotification",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "sendNotification",
    data: BytesLike
  ): Result;
}

export namespace NotificationSentEvent {
  export type InputTuple = [
    channel: AddressLike,
    recipient: AddressLike,
    identity: BytesLike
  ];
  export type OutputTuple = [
    channel: string,
    recipient: string,
    identity: string
  ];
  export interface OutputObject {
    channel: string;
    recipient: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockPushComm extends BaseContract {
  connect(runner?: ContractRunner | null): MockPushComm;
  waitForDeployment(): Promise<this>;

  interface: MockPushCommInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  sendNotification: TypedContractMethod<
    [_channel: AddressLike, _recipient: AddressLike, _identity: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "sendNotification"
  ): TypedContractMethod<
    [_channel: AddressLike, _recipient: AddressLike, _identity: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "NotificationSent"
  ): TypedContractEvent<
    NotificationSentEvent.InputTuple,
    NotificationSentEvent.OutputTuple,
    NotificationSentEvent.OutputObject
  >;

  filters: {
    "NotificationSent(address,address,bytes)": TypedContractEvent<
      NotificationSentEvent.InputTuple,
      NotificationSentEvent.OutputTuple,
      NotificationSentEvent.OutputObject
    >;
    NotificationSent: TypedContractEvent<
      NotificationSentEvent.InputTuple,
      NotificationSentEvent.OutputTuple,
      NotificationSentEvent.OutputObject
    >;
  };
}
